### ISSUE TITLE
Suggestion: Microphone icon visibility

### ISSUE THREAD

**Issue by Jiroga** [BlueberryWolf/ReelChat#2]
As it stands, the microphone icon on the bottom right is always visible regardless of the HUD's status (visible/invisible). Would it be at all possible for the icon's visibility to also be toggleable along with the rest of the hud? It would be fantastic for taking screenshots while still having the mod enabled. :>

Thank you, and have a great day!

**Comment by BlueberryWolf** [comment]
Hi! thanks for submitting an issue. I just fixed the mod for the latest version, and also made the visibility toggleable. Expect my APIs and ReelChat to be on thunderstore and updated in a second here

**Comment by BlueberryWolf** [comment]
There, done! UI is now hidden when you press h.
